#!/bin/bash
# Git commit by base
TOP=$(git rev-parse --show-toplevel);
PREFIX=$(git rev-parse --show-prefix);

# get first dirname
if [[ $PREFIX == "" ]];
then
    BASE=$(basename $TOP);
else
    BASE=$(basename $(cut -d '/' -f1 <<< $PREFIX));
fi;

if [[ $? == 0 ]];
then
    git commit -m "$BASE: $1";
else
    echo "Fail to process!" >&2;
fi;
